apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: data-pipeline
data:
  localRegistryHosting.v1: |
    host: "localhost:5001"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
